### ISSUE TITLE
future instead of foreach please

### ISSUE THREAD

**Issue by tdhock** [anujkhare/iregnet#69]
Hi in recent years it has become apparent that the future framework should be preferred over foreach, so I would suggest using `future.apply::future_lapply` instead of foreach in cv.iregnet. For a usage example see https://github.com/tdhock/penaltyLearning/blob/master/R/IntervalRegression.R#L192

is that ok with you @anujkhare ?

is that something you could implement in a new PR this summer? @theadityasam

**Comment by theadityasam** [comment]
Yes, will look into it

**Comment by theadityasam** [comment]
https://github.com/anujkhare/iregnet/blob/master/R/cv.iregnet.R#L119
